//
//  NotificationsDefine.h
//  车联网-修理厂端
//
//  Created by AnYanbo on 16/6/6.
//  Copyright © 2016年 AnYanbo. All rights reserved.
//

#ifndef NotificationsDefine_h
#define NotificationsDefine_h

#define NOTIFICATION_SHOP_CONSULT_SUCCESS               (@"NOTIFICATION_SHOP_CONSULT_SUCCESS")

#define NOTIFICATION_SHOP_CART_UPDATE                   (@"NOTIFICATION_SHOP_CART_UPDATE")

#define NOTIFICATION_FAVORITE_STORE_ADD                 (@"NOTIFICATION_FAVORITE_STORE_ADD")
#define NOTIFICATION_FAVORITE_STORE_DELETE              (@"NOTIFICATION_FAVORITE_STORE_DELETE")

#define NOTIFICATION_USER_ADDRESS_ADD                   (@"NOTIFICATION_USER_ADDRESS_ADD")

#define NOTIFICATION_USER_WALLET_INFO_UPDATE            (@"NOTIFICATION_USER_WALLET_INFO_UPDATE")

#define NOTIFICATION_USER_NEED_LOGIN                    (@"NOTIFICATION_USER_NEED_LOGIN")
#define NOTIFICATION_USER_LOGIN_SUCCESS                 (@"NOTIFICATION_USER_LOGIN_SUCCESS")
#define NOTIFICATION_USER_LOGOUT                        (@"NOTIFICATION_USER_LOGOUT")
#define NOTIFICATION_HOME_WANT_BUY_ITEM                 (@"NOTIFICATION_HOME_WANT_BUY_ITEM")

#define NOTIFICATION_USER_LOGIN_SUCCESS                 (@"NOTIFICATION_USER_LOGIN_SUCCESS")
#define NOTIFICATION_USER_LOGOUT                        (@"NOTIFICATION_USER_LOGOUT")
#define NOTIFICATION_USER_INFO_UPDATE                   (@"NOTIFICATION_USER_INFO_UPDATE")
#define NOTIFICATION_CLICK_NAV_USER_CENTER              (@"NOTIFICATION_CLICK_NAV_USER_CENTER")
#define NOTIFICATION_WANT_GO_LIST_UPDATE                (@"NOTIFICATION_WANT_GO_LIST_UPDATE")
#define NOTIFICATION_MY_PACKAGE_LIST_UPDATE             (@"NOTIFICATION_MY_PACKAGE_LIST_UPDATE")
#define NOTIFICATION_AREA_INFO_UPDATE                   (@"NOTIFICATION_AREA_INFO_UPDATE")

#endif /* NotificationsDefine_h */
